apiVersion: v1
kind: policy
spec:
  name: Ensure a password is required to wake the computer from sleep or screen saver is enabled
  platforms: macOS
  platform: darwin
  description: Checks that password is required to wake the computer from sleep or screen saver is enabled.
  resolution: |
    Automated method:
    Ask your system administrator to deploy an MDM profile that ensures a password is required to wake the computer from sleep or screen saver is enabled.
    Graphical method:
      Perform the following steps to ensure a password is required to wake the computer from sleep or screen saver is enabled:
        1. Open System Settings
        2. Select Lock Screen
        3. Verify that "Require password after screensaver begins or display is turned
        off" is set with "After 0 seconds" or "After 5 seconds"
  query: |-
    SELECT 1 WHERE 
      EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPassword' AND 
            (value = 1 OR value = 'true') AND 
            username = ''
        )
      AND EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPasswordDelay' AND 
            value <= 5 AND 
            username = ''
        )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPassword' AND 
            (value != 1 AND value != 'true')
        )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPasswordDelay' AND 
            value > 5
        );  
  purpose: Informational
  tags: compliance, CIS, CIS_Level1, premium,
  contributors: sharon-fdm,ddribeiro
  configuration_profile: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>PayloadContent</key>
      <array>
        <dict>
          <key>PayloadDisplayName</key>
          <string>Screensaver</string>
          <key>PayloadIdentifier</key>
          <string>com.apple.screensaver.AB633B1B-EAEF-4AB6-B5F6-DE67193267E9</string>
          <key>PayloadType</key>
          <string>com.apple.screensaver</string>
          <key>PayloadUUID</key>
          <string>AB633B1B-EAEF-4AB6-B5F6-DE67193267E9</string>
          <key>PayloadVersion</key>
          <integer>1</integer>
          <key>askForPassword</key>
          <true/>
          <key>askForPasswordDelay</key>
          <integer>0</integer>
        </dict>
      </array>
      <key>PayloadDisplayName</key>
      <string>Require password after screensaver or sleep</string>
      <key>PayloadIdentifier</key>
      <string>com.fleetdm.password_policy</string>
      <key>PayloadType</key>
      <string>Configuration</string>
      <key>PayloadUUID</key>
      <string>5A2DC0F2-C5FE-4808-9083-D9879684D7FA</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
    </dict>
    </plist>
---
apiVersion: v1
kind: policy
spec:
  name: Ensure auto-update is enabled
  platforms: macOS
  platform: darwin
  description: Checks that the system is configured via MDM to automatically install updates.
  resolution: "Ask your system administrator to deploy an MDM profile that enables automatic updates."
  query: |
    SELECT 1 WHERE 
      EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.SoftwareUpdate' AND 
            name='AutomaticCheckEnabled' AND 
            (value = 1 OR value = 'true') AND 
            username = ''
        )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.SoftwareUpdate' AND 
            name='AutomaticCheckEnabled' AND 
            (value != 1 AND value != 'true')
        );  
  purpose: Informational
  tags: compliance, CIS, CIS_Level1, premium
  contributors: sharon-fdm,ddribeiro
  configuration_profile: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>PayloadContent</key>
      <array>
        <dict>
          <key>AutomaticCheckEnabled</key>
          <true/>
          <key>PayloadDisplayName</key>
          <string>Software Update</string>
          <key>PayloadIdentifier</key>
          <string>com.apple.SoftwareUpdate.8567CAE0-4F08-49B7-9DEE-EE7A1FB232E4</string>
          <key>PayloadType</key>
          <string>com.apple.SoftwareUpdate</string>
          <key>PayloadUUID</key>
          <string>8567CAE0-4F08-49B7-9DEE-EE7A1FB232E4</string>
          <key>PayloadVersion</key>
          <integer>1</integer>
        </dict>
      </array>
      <key>PayloadDisplayName</key>
      <string>Automatically install updates</string>
      <key>PayloadIdentifier</key>
      <string>com.fleetdm.automatically_install_updates</string>
      <key>PayloadType</key>
      <string>Configuration</string>
      <key>PayloadUUID</key>
      <string>C9797096-D3DD-4BB4-85B0-6679209BA78F</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
    </dict>
    </plist>
---
apiVersion: v1
kind: policy
spec:
  name: Screen lock enabled (Windows)
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\InactivityTimeoutSecs' AND CAST(data as INTEGER) <= 1800;
  description: "Checks if the screen lock is enabled and configured to lock the system within 30 minutes or less."
  resolution: "Contact your IT administrator to enable the Interactive Logon: Machine inactivity limit setting with a value of 1800 seconds or lower."
  powershell: |
    $regPath = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
    $value = (Get-ItemProperty -Path $regPath -Name 'InactivityTimeoutSecs' -ErrorAction SilentlyContinue).InactivityTimeoutSecs
    if ($value -and ([int]$value) -le 1800) {
        Write-Output 1
    } else {
        Write-Output 0
    }
  tags: compliance, hardening, built-in
  platform: windows
  contributors: GuillaumeRoss