name: Check Markdown files

# This action is used to check that documentation adheres to style guidelines.

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.md"
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  check-markdown-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Verify Markdown documentation is free of "here" and "click here" link anchors
        run: |
          BAD_LINK_LINES=$(grep -Eir --exclude-dir=node_modules --include=\*.md '\[(click )?here\]' .)
          if [[ -n "$BAD_LINK_LINES" ]]; then
            echo '❌ fail: links found with "here" or "click here" anchors in Markdown files'
            echo "$BAD_LINK_LINES"
            exit 1
          fi
