name: Generate maintained app data

permissions:
  contents: write

on:
  pull_request:
    paths:
      - "ee/maintained-apps/inputs/**.json"
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      # TODO(JVE): uncomment this
      # - name: Harden Runner
      #   uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      #   with:
      #     egress-policy: audit

      - name: Checkout Fleet
        uses: actions/checkout@v4
        with:
          repository: fleetdm/fleet
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          path: fleet

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          cache: false
          go-version: '^1.23.4'

      - name: Generate maintained app data
        run: |
          cd fleet
          go mod download
          git diff --name-only --diff-filter=AM origin/main | grep "ee/maintained-apps/inputs/.*\.json" | while read -r; do go run cmd/maintained-apps/main.go -file=$REPLY; done
      - name: Commit generated manifest data
        run: |
          cd fleet
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add -A
          git commit -m "Generated manifest data"
          git push