name: goreleaser-test

on:
  push:
    branches:
      - sgress454/23825-use-tag-when-attesting-image-test
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  goreleaser:
    runs-on: ubuntu-20.04-4-cores
    environment: Docker Hub
    permissions:
      contents: write
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0 # Needed for goreleaser
      
      - name: Copy artifacts file
        run: |
          mkdir ./dist
          cp ./.github/workflows/config/artifacts.json ./dist/artifacts.json

      - name: Get tag
        run: |
          echo "TAG=v4.63.0" >> $GITHUB_OUTPUT
        id: docker

      # Get the image digests from the goreleaser artifacts
      # Adapted from https://github.com/goreleaser/goreleaser/issues/4852#issuecomment-2122790132
      - name: Get image digests
        continue-on-error: true
        id: image_digests
        run: |
          digest_fleet=$(cat ./dist/artifacts.json | jq -r 'first(.[]|select(.type == "Published Docker Image" and (.name == "fleetdm/fleet:${{ steps.docker.outputs.tag }}")) | select(. != null)|.extra.Digest)')
          echo "digest_fleet=$digest_fleet" >> "$GITHUB_OUTPUT"
          digest_fleetctl=$(cat ./dist/artifacts.json | jq -r 'first(.[]|select(.type == "Published Docker Image" and (.name  == "fleetdm/fleetctl:${{ steps.docker.outputs.tag }}")) | select(. != null)|.extra.Digest)')
          echo "digest_fleetctl=$digest_fleetctl" >> "$GITHUB_OUTPUT"

      - name: Verify digests
        run: |
          echo fleet: ${{steps.image_digests.outputs.digest_fleet}} fleetctl: ${{steps.image_digests.outputs.digest_fleetctl}}

      