name: Ingest maintained apps

# TODO(JVE): add schedule/other triggers
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      # TODO(JVE): uncomment this
      # - name: Harden Runner
      #   uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      #   with:
      #     egress-policy: audit

      - name: Checkout Fleet
        uses: actions/checkout@v4
        with:
          repository: fleetdm/fleet
          fetch-depth: 1
          ref: 26083-fma-ingest-action
          path: fleet

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          cache: false
          go-version: '^1.23.4'

      - name: Ingest maintained apps
        run: |
          cd fleet
          go mod download
          go run cmd/maintained-apps/main.go

      # TODO(JVE): need to finalize the contents/title of this PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          path: fleet
          branch: jve-testing-pr-from-action
          delete-branch: true
          title: "[DO NOT MERGE] this is a test of creating PRs from actions"
          commit-message: |
            Ingest Fleet-maintained apps.

            Generated automatically with cmd/maintained-apps
          body: Automated change from GitHub action (still in development)


