name: Test vars
on:
  push:
    branches:
      - sgress454/test-dogfood-github-idp-xml
  workflow_dispatch: # manual

# This allows a subsequently queued workflow run to interrupt previous runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

env:
  AWS_REGION: us-east-2
  AWS_IAM_ROLE: arn:aws:iam::160035666661:role/github-actions-role

permissions:
  contents: read
  id-token: write # for aws-actions/configure-aws-credentials


jobs:
  send_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up secret file
        env:
          DOGFOOD_SSO_METADATA: ${{ secrets.DOGFOOD_SSO_METADATA }}
          DOGFOOD_END_USER_SSO_METADATA: ${{ secrets.DOGFOOD_END_USER_SSO_METADATA }}
        run: |
          echo "$DOGFOOD_SSO_METADATA" >> ./secrets.txt
          echo "" >> ./secrets.txt
          echo "$DOGFOOD_END_USER_SSO_METADATA" >> ./secrets.txt

      - name: Upload
        run: aws s3 cp ./secrets.txt s3://fleet-test-1/secrets.txt 

